package com.entity;

public class LogisticsManager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_manager.mgID
     *
     * @mbg.generated
     */
    private String mgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_manager.roleID
     *
     * @mbg.generated
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_manager.managerName
     *
     * @mbg.generated
     */
    private String managername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_manager.managerSex
     *
     * @mbg.generated
     */
    private String managersex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_manager.Tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_manager.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_manager.COMMENT
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_manager.mgID
     *
     * @return the value of logistics_manager.mgID
     *
     * @mbg.generated
     */
    public String getMgid() {
        return mgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_manager.mgID
     *
     * @param mgid the value for logistics_manager.mgID
     *
     * @mbg.generated
     */
    public void setMgid(String mgid) {
        this.mgid = mgid == null ? null : mgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_manager.roleID
     *
     * @return the value of logistics_manager.roleID
     *
     * @mbg.generated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_manager.roleID
     *
     * @param roleid the value for logistics_manager.roleID
     *
     * @mbg.generated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_manager.managerName
     *
     * @return the value of logistics_manager.managerName
     *
     * @mbg.generated
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_manager.managerName
     *
     * @param managername the value for logistics_manager.managerName
     *
     * @mbg.generated
     */
    public void setManagername(String managername) {
        this.managername = managername == null ? null : managername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_manager.managerSex
     *
     * @return the value of logistics_manager.managerSex
     *
     * @mbg.generated
     */
    public String getManagersex() {
        return managersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_manager.managerSex
     *
     * @param managersex the value for logistics_manager.managerSex
     *
     * @mbg.generated
     */
    public void setManagersex(String managersex) {
        this.managersex = managersex == null ? null : managersex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_manager.Tel
     *
     * @return the value of logistics_manager.Tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_manager.Tel
     *
     * @param tel the value for logistics_manager.Tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_manager.Address
     *
     * @return the value of logistics_manager.Address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_manager.Address
     *
     * @param address the value for logistics_manager.Address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_manager.COMMENT
     *
     * @return the value of logistics_manager.COMMENT
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_manager.COMMENT
     *
     * @param comment the value for logistics_manager.COMMENT
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}