package com.entity;

import java.util.Date;

public class LogisticsCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_car.carID
     *
     * @mbg.generated
     */
    private String carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_car.routeID
     *
     * @mbg.generated
     */
    private String routeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_car.carType
     *
     * @mbg.generated
     */
    private String cartype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_car.carOrign
     *
     * @mbg.generated
     */
    private String carorign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_car.carProDate
     *
     * @mbg.generated
     */
    private Date carprodate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_car.carBuyDate
     *
     * @mbg.generated
     */
    private Date carbuydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_car.carCapacity
     *
     * @mbg.generated
     */
    private Integer carcapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_car.carState
     *
     * @mbg.generated
     */
    private Boolean carstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_car.COMMENT
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_car.carID
     *
     * @return the value of logistics_car.carID
     *
     * @mbg.generated
     */
    public String getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_car.carID
     *
     * @param carid the value for logistics_car.carID
     *
     * @mbg.generated
     */
    public void setCarid(String carid) {
        this.carid = carid == null ? null : carid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_car.routeID
     *
     * @return the value of logistics_car.routeID
     *
     * @mbg.generated
     */
    public String getRouteid() {
        return routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_car.routeID
     *
     * @param routeid the value for logistics_car.routeID
     *
     * @mbg.generated
     */
    public void setRouteid(String routeid) {
        this.routeid = routeid == null ? null : routeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_car.carType
     *
     * @return the value of logistics_car.carType
     *
     * @mbg.generated
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_car.carType
     *
     * @param cartype the value for logistics_car.carType
     *
     * @mbg.generated
     */
    public void setCartype(String cartype) {
        this.cartype = cartype == null ? null : cartype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_car.carOrign
     *
     * @return the value of logistics_car.carOrign
     *
     * @mbg.generated
     */
    public String getCarorign() {
        return carorign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_car.carOrign
     *
     * @param carorign the value for logistics_car.carOrign
     *
     * @mbg.generated
     */
    public void setCarorign(String carorign) {
        this.carorign = carorign == null ? null : carorign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_car.carProDate
     *
     * @return the value of logistics_car.carProDate
     *
     * @mbg.generated
     */
    public Date getCarprodate() {
        return carprodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_car.carProDate
     *
     * @param carprodate the value for logistics_car.carProDate
     *
     * @mbg.generated
     */
    public void setCarprodate(Date carprodate) {
        this.carprodate = carprodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_car.carBuyDate
     *
     * @return the value of logistics_car.carBuyDate
     *
     * @mbg.generated
     */
    public Date getCarbuydate() {
        return carbuydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_car.carBuyDate
     *
     * @param carbuydate the value for logistics_car.carBuyDate
     *
     * @mbg.generated
     */
    public void setCarbuydate(Date carbuydate) {
        this.carbuydate = carbuydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_car.carCapacity
     *
     * @return the value of logistics_car.carCapacity
     *
     * @mbg.generated
     */
    public Integer getCarcapacity() {
        return carcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_car.carCapacity
     *
     * @param carcapacity the value for logistics_car.carCapacity
     *
     * @mbg.generated
     */
    public void setCarcapacity(Integer carcapacity) {
        this.carcapacity = carcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_car.carState
     *
     * @return the value of logistics_car.carState
     *
     * @mbg.generated
     */
    public Boolean getCarstate() {
        return carstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_car.carState
     *
     * @param carstate the value for logistics_car.carState
     *
     * @mbg.generated
     */
    public void setCarstate(Boolean carstate) {
        this.carstate = carstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_car.COMMENT
     *
     * @return the value of logistics_car.COMMENT
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_car.COMMENT
     *
     * @param comment the value for logistics_car.COMMENT
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}