package com.entity;

import java.util.Date;

public class LogisticsCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_customer.cuID
     *
     * @mbg.generated
     */
    private String cuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_customer.customerName
     *
     * @mbg.generated
     */
    private String customername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_customer.customerPsd
     *
     * @mbg.generated
     */
    private String customerpsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_customer.customerSex
     *
     * @mbg.generated
     */
    private String customersex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_customer.Brithday
     *
     * @mbg.generated
     */
    private Date brithday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_customer.Tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_customer.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_customer.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_customer.cuID
     *
     * @return the value of logistics_customer.cuID
     *
     * @mbg.generated
     */
    public String getCuid() {
        return cuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_customer.cuID
     *
     * @param cuid the value for logistics_customer.cuID
     *
     * @mbg.generated
     */
    public void setCuid(String cuid) {
        this.cuid = cuid == null ? null : cuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_customer.customerName
     *
     * @return the value of logistics_customer.customerName
     *
     * @mbg.generated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_customer.customerName
     *
     * @param customername the value for logistics_customer.customerName
     *
     * @mbg.generated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_customer.customerPsd
     *
     * @return the value of logistics_customer.customerPsd
     *
     * @mbg.generated
     */
    public String getCustomerpsd() {
        return customerpsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_customer.customerPsd
     *
     * @param customerpsd the value for logistics_customer.customerPsd
     *
     * @mbg.generated
     */
    public void setCustomerpsd(String customerpsd) {
        this.customerpsd = customerpsd == null ? null : customerpsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_customer.customerSex
     *
     * @return the value of logistics_customer.customerSex
     *
     * @mbg.generated
     */
    public String getCustomersex() {
        return customersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_customer.customerSex
     *
     * @param customersex the value for logistics_customer.customerSex
     *
     * @mbg.generated
     */
    public void setCustomersex(String customersex) {
        this.customersex = customersex == null ? null : customersex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_customer.Brithday
     *
     * @return the value of logistics_customer.Brithday
     *
     * @mbg.generated
     */
    public Date getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_customer.Brithday
     *
     * @param brithday the value for logistics_customer.Brithday
     *
     * @mbg.generated
     */
    public void setBrithday(Date brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_customer.Tel
     *
     * @return the value of logistics_customer.Tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_customer.Tel
     *
     * @param tel the value for logistics_customer.Tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_customer.Address
     *
     * @return the value of logistics_customer.Address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_customer.Address
     *
     * @param address the value for logistics_customer.Address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_customer.Comment
     *
     * @return the value of logistics_customer.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_customer.Comment
     *
     * @param comment the value for logistics_customer.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}