package com.entity;

import java.math.BigDecimal;

public class LogisticsOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.orderID
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.carID
     *
     * @mbg.generated
     */
    private String carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.cuID
     *
     * @mbg.generated
     */
    private String cuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.postPName
     *
     * @mbg.generated
     */
    private String postpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.postPTel
     *
     * @mbg.generated
     */
    private String postptel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.postPaddr
     *
     * @mbg.generated
     */
    private String postpaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.getPName
     *
     * @mbg.generated
     */
    private String getpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.getPTel
     *
     * @mbg.generated
     */
    private String getptel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.getPaddr
     *
     * @mbg.generated
     */
    private String getpaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.goodsName
     *
     * @mbg.generated
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.goodsWeight
     *
     * @mbg.generated
     */
    private Integer goodsweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.orderType
     *
     * @mbg.generated
     */
    private String ordertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.orderState
     *
     * @mbg.generated
     */
    private String orderstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.transportPrice
     *
     * @mbg.generated
     */
    private BigDecimal transportprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.deliveryPrice
     *
     * @mbg.generated
     */
    private BigDecimal deliveryprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.totalPrice
     *
     * @mbg.generated
     */
    private String totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_order.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.orderID
     *
     * @return the value of logistics_order.orderID
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.orderID
     *
     * @param orderid the value for logistics_order.orderID
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.carID
     *
     * @return the value of logistics_order.carID
     *
     * @mbg.generated
     */
    public String getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.carID
     *
     * @param carid the value for logistics_order.carID
     *
     * @mbg.generated
     */
    public void setCarid(String carid) {
        this.carid = carid == null ? null : carid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.cuID
     *
     * @return the value of logistics_order.cuID
     *
     * @mbg.generated
     */
    public String getCuid() {
        return cuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.cuID
     *
     * @param cuid the value for logistics_order.cuID
     *
     * @mbg.generated
     */
    public void setCuid(String cuid) {
        this.cuid = cuid == null ? null : cuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.postPName
     *
     * @return the value of logistics_order.postPName
     *
     * @mbg.generated
     */
    public String getPostpname() {
        return postpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.postPName
     *
     * @param postpname the value for logistics_order.postPName
     *
     * @mbg.generated
     */
    public void setPostpname(String postpname) {
        this.postpname = postpname == null ? null : postpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.postPTel
     *
     * @return the value of logistics_order.postPTel
     *
     * @mbg.generated
     */
    public String getPostptel() {
        return postptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.postPTel
     *
     * @param postptel the value for logistics_order.postPTel
     *
     * @mbg.generated
     */
    public void setPostptel(String postptel) {
        this.postptel = postptel == null ? null : postptel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.postPaddr
     *
     * @return the value of logistics_order.postPaddr
     *
     * @mbg.generated
     */
    public String getPostpaddr() {
        return postpaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.postPaddr
     *
     * @param postpaddr the value for logistics_order.postPaddr
     *
     * @mbg.generated
     */
    public void setPostpaddr(String postpaddr) {
        this.postpaddr = postpaddr == null ? null : postpaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.getPName
     *
     * @return the value of logistics_order.getPName
     *
     * @mbg.generated
     */
    public String getGetpname() {
        return getpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.getPName
     *
     * @param getpname the value for logistics_order.getPName
     *
     * @mbg.generated
     */
    public void setGetpname(String getpname) {
        this.getpname = getpname == null ? null : getpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.getPTel
     *
     * @return the value of logistics_order.getPTel
     *
     * @mbg.generated
     */
    public String getGetptel() {
        return getptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.getPTel
     *
     * @param getptel the value for logistics_order.getPTel
     *
     * @mbg.generated
     */
    public void setGetptel(String getptel) {
        this.getptel = getptel == null ? null : getptel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.getPaddr
     *
     * @return the value of logistics_order.getPaddr
     *
     * @mbg.generated
     */
    public String getGetpaddr() {
        return getpaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.getPaddr
     *
     * @param getpaddr the value for logistics_order.getPaddr
     *
     * @mbg.generated
     */
    public void setGetpaddr(String getpaddr) {
        this.getpaddr = getpaddr == null ? null : getpaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.goodsName
     *
     * @return the value of logistics_order.goodsName
     *
     * @mbg.generated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.goodsName
     *
     * @param goodsname the value for logistics_order.goodsName
     *
     * @mbg.generated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.goodsWeight
     *
     * @return the value of logistics_order.goodsWeight
     *
     * @mbg.generated
     */
    public Integer getGoodsweight() {
        return goodsweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.goodsWeight
     *
     * @param goodsweight the value for logistics_order.goodsWeight
     *
     * @mbg.generated
     */
    public void setGoodsweight(Integer goodsweight) {
        this.goodsweight = goodsweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.orderType
     *
     * @return the value of logistics_order.orderType
     *
     * @mbg.generated
     */
    public String getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.orderType
     *
     * @param ordertype the value for logistics_order.orderType
     *
     * @mbg.generated
     */
    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype == null ? null : ordertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.orderState
     *
     * @return the value of logistics_order.orderState
     *
     * @mbg.generated
     */
    public String getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.orderState
     *
     * @param orderstate the value for logistics_order.orderState
     *
     * @mbg.generated
     */
    public void setOrderstate(String orderstate) {
        this.orderstate = orderstate == null ? null : orderstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.transportPrice
     *
     * @return the value of logistics_order.transportPrice
     *
     * @mbg.generated
     */
    public BigDecimal getTransportprice() {
        return transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.transportPrice
     *
     * @param transportprice the value for logistics_order.transportPrice
     *
     * @mbg.generated
     */
    public void setTransportprice(BigDecimal transportprice) {
        this.transportprice = transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.deliveryPrice
     *
     * @return the value of logistics_order.deliveryPrice
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryprice() {
        return deliveryprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.deliveryPrice
     *
     * @param deliveryprice the value for logistics_order.deliveryPrice
     *
     * @mbg.generated
     */
    public void setDeliveryprice(BigDecimal deliveryprice) {
        this.deliveryprice = deliveryprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.totalPrice
     *
     * @return the value of logistics_order.totalPrice
     *
     * @mbg.generated
     */
    public String getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.totalPrice
     *
     * @param totalprice the value for logistics_order.totalPrice
     *
     * @mbg.generated
     */
    public void setTotalprice(String totalprice) {
        this.totalprice = totalprice == null ? null : totalprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_order.Comment
     *
     * @return the value of logistics_order.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_order.Comment
     *
     * @param comment the value for logistics_order.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}