package com.dao;

import com.entity.LogisticsPrivance;
import java.util.List;

public interface LogisticsPrivanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_privance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String provinceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_privance
     *
     * @mbg.generated
     */
    int insert(LogisticsPrivance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_privance
     *
     * @mbg.generated
     */
    LogisticsPrivance selectByPrimaryKey(String provinceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_privance
     *
     * @mbg.generated
     */
    List<LogisticsPrivance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_privance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogisticsPrivance record);
}