package com.dao;

import com.entity.LogisticsCityarea;
import java.util.List;

public interface LogisticsCityareaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_cityarea
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_cityarea
     *
     * @mbg.generated
     */
    int insert(LogisticsCityarea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_cityarea
     *
     * @mbg.generated
     */
    LogisticsCityarea selectByPrimaryKey(String areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_cityarea
     *
     * @mbg.generated
     */
    List<LogisticsCityarea> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_cityarea
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogisticsCityarea record);
}