package com.dao;

import com.entity.LogisticsCustomer;
import java.util.List;

public interface LogisticsCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_customer
     *
     * @mbg.generated
     */
    int insert(LogisticsCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_customer
     *
     * @mbg.generated
     */
    LogisticsCustomer selectByPrimaryKey(String cuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_customer
     *
     * @mbg.generated
     */
    List<LogisticsCustomer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogisticsCustomer record);
}