package com.dao;

import com.entity.LogisticsCar;
import java.util.List;

public interface LogisticsCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_car
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String carid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_car
     *
     * @mbg.generated
     */
    int insert(LogisticsCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_car
     *
     * @mbg.generated
     */
    LogisticsCar selectByPrimaryKey(String carid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_car
     *
     * @mbg.generated
     */
    List<LogisticsCar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_car
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogisticsCar record);
}