package com.dao;

import com.entity.LogisticsDeliveryrange;
import java.util.List;

public interface LogisticsDeliveryrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_deliveryrange
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rangeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_deliveryrange
     *
     * @mbg.generated
     */
    int insert(LogisticsDeliveryrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_deliveryrange
     *
     * @mbg.generated
     */
    LogisticsDeliveryrange selectByPrimaryKey(String rangeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_deliveryrange
     *
     * @mbg.generated
     */
    List<LogisticsDeliveryrange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_deliveryrange
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogisticsDeliveryrange record);
}