package com.dao;

import com.entity.LogisticsDeliveryplace;
import java.util.List;

public interface LogisticsDeliveryplaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_deliveryplace
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String depid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_deliveryplace
     *
     * @mbg.generated
     */
    int insert(LogisticsDeliveryplace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_deliveryplace
     *
     * @mbg.generated
     */
    LogisticsDeliveryplace selectByPrimaryKey(String depid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_deliveryplace
     *
     * @mbg.generated
     */
    List<LogisticsDeliveryplace> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_deliveryplace
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogisticsDeliveryplace record);
}