package com.dao;

import com.entity.LogisticsRole;
import java.util.List;

public interface LogisticsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_role
     *
     * @mbg.generated
     */
    int insert(LogisticsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_role
     *
     * @mbg.generated
     */
    LogisticsRole selectByPrimaryKey(String roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_role
     *
     * @mbg.generated
     */
    List<LogisticsRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogisticsRole record);
}