package com.dao;

import com.entity.LogisticsOrder;
import java.util.List;

public interface LogisticsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_order
     *
     * @mbg.generated
     */
    int insert(LogisticsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_order
     *
     * @mbg.generated
     */
    LogisticsOrder selectByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_order
     *
     * @mbg.generated
     */
    List<LogisticsOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogisticsOrder record);
}